/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoCreateUserRequest,
  HttperrorUnprocessableEntityApiResponse,
} from '../models/index';
import {
    DtoCreateUserRequestFromJSON,
    DtoCreateUserRequestToJSON,
    HttperrorUnprocessableEntityApiResponseFromJSON,
    HttperrorUnprocessableEntityApiResponseToJSON,
} from '../models/index';

export interface UsersPostRequest {
    data: DtoCreateUserRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create user by email address
     */
    async usersPostRaw(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling usersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoCreateUserRequestToJSON(requestParameters['data']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create user by email address
     */
    async usersPost(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersPostRaw(requestParameters, initOverrides);
    }

}
