/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as WorkspacesImport } from './routes/_workspaces'
import { Route as WorkspacesIndexImport } from './routes/workspaces/index'
import { Route as WorkspacesWorkspaceIdImport } from './routes/workspaces/$workspaceId'
import { Route as JoinWorkspaceIdImport } from './routes/join/$workspaceId'
import { Route as WorkspacesWorkspaceIdChannelsChannelIdImport } from './routes/workspaces/$workspaceId/channels/$channelId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesRoute = WorkspacesImport.update({
  id: '/_workspaces',
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesIndexRoute = WorkspacesIndexImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

const JoinWorkspaceIdRoute = JoinWorkspaceIdImport.update({
  id: '/join/$workspaceId',
  path: '/join/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesWorkspaceIdChannelsChannelIdRoute =
  WorkspacesWorkspaceIdChannelsChannelIdImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspaces': {
      id: '/_workspaces'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WorkspacesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/join/$workspaceId': {
      id: '/join/$workspaceId'
      path: '/join/$workspaceId'
      fullPath: '/join/$workspaceId'
      preLoaderRoute: typeof JoinWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesIndexImport
      parentRoute: typeof rootRoute
    }
    '/workspaces/$workspaceId/channels/$channelId': {
      id: '/workspaces/$workspaceId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/workspaces/$workspaceId/channels/$channelId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdImport
      parentRoute: typeof WorkspacesWorkspaceIdImport
    }
  }
}

// Create and export the route tree

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdChannelsChannelIdRoute: typeof WorkspacesWorkspaceIdChannelsChannelIdRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdChannelsChannelIdRoute:
    WorkspacesWorkspaceIdChannelsChannelIdRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

export interface FileRoutesByFullPath {
  '': typeof WorkspacesRoute
  '/login': typeof LoginRoute
  '/join/$workspaceId': typeof JoinWorkspaceIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/channels/$channelId': typeof WorkspacesWorkspaceIdChannelsChannelIdRoute
}

export interface FileRoutesByTo {
  '': typeof WorkspacesRoute
  '/login': typeof LoginRoute
  '/join/$workspaceId': typeof JoinWorkspaceIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/channels/$channelId': typeof WorkspacesWorkspaceIdChannelsChannelIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_workspaces': typeof WorkspacesRoute
  '/login': typeof LoginRoute
  '/join/$workspaceId': typeof JoinWorkspaceIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/channels/$channelId': typeof WorkspacesWorkspaceIdChannelsChannelIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/join/$workspaceId'
    | '/workspaces/$workspaceId'
    | '/workspaces'
    | '/workspaces/$workspaceId/channels/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/join/$workspaceId'
    | '/workspaces/$workspaceId'
    | '/workspaces'
    | '/workspaces/$workspaceId/channels/$channelId'
  id:
    | '__root__'
    | '/_workspaces'
    | '/login'
    | '/join/$workspaceId'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/workspaces/$workspaceId/channels/$channelId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WorkspacesRoute: typeof WorkspacesRoute
  LoginRoute: typeof LoginRoute
  JoinWorkspaceIdRoute: typeof JoinWorkspaceIdRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  WorkspacesRoute: WorkspacesRoute,
  LoginRoute: LoginRoute,
  JoinWorkspaceIdRoute: JoinWorkspaceIdRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_workspaces",
        "/login",
        "/join/$workspaceId",
        "/workspaces/$workspaceId",
        "/workspaces/"
      ]
    },
    "/_workspaces": {
      "filePath": "_workspaces.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/join/$workspaceId": {
      "filePath": "join/$workspaceId.tsx"
    },
    "/workspaces/$workspaceId": {
      "filePath": "workspaces/$workspaceId.tsx",
      "children": [
        "/workspaces/$workspaceId/channels/$channelId"
      ]
    },
    "/workspaces/": {
      "filePath": "workspaces/index.tsx"
    },
    "/workspaces/$workspaceId/channels/$channelId": {
      "filePath": "workspaces/$workspaceId/channels/$channelId.tsx",
      "parent": "/workspaces/$workspaceId"
    }
  }
}
ROUTE_MANIFEST_END */
