/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as WorkspacesWorkspaceIdImport } from './routes/workspaces/$workspaceId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdImport.update({
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/workspaces/$workspaceId'
  id: '__root__' | '/login' | '/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/workspaces/$workspaceId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/workspaces/$workspaceId": {
      "filePath": "workspaces/$workspaceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
