openapi: 3.0.0
info:
  title: User API
  description: API to create a new user
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
paths:
  /users:
    post:
      summary: Create a new user
      description: Create a new user with the given details
      operationId: createUser
      requestBody:
        description: User object to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'     
components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          description: The user's name
          example: "John Doe"
        email:
          type: string
          description: The user's email address
          example: "john.doe@example.com"
        password:
          type: string
          description: The user's password
          example: "securePassword123"
      required:
        - email
        - password
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the user
          example: "12345"
        email:
          type: string
          description: The user's email address
          example: "john.doe@example.com"

