definitions:
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  httperror.UnprocessableEntityApiResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/httperror.UnprocessableEntityApiResponse'
      summary: Create user by email address
swagger: "2.0"
