// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dto

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Email The user's email address
	Email string `json:"email"`

	// Name The user's name
	Name string `json:"name"`

	// Password The user's password
	Password string `json:"password"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest
