/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelMessageResponse
 */
export interface ChannelMessageResponse {
    /**
     * 
     * @type {number}
     * @memberof ChannelMessageResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    attachment: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    username: string;
    /**
     * 
     * @type {number}
     * @memberof ChannelMessageResponse
     */
    senderId: number;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    avatar?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ChannelMessageResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChannelMessageResponse
     */
    updateAt: Date;
}

/**
 * Check if a given object implements the ChannelMessageResponse interface.
 */
export function instanceOfChannelMessageResponse(value: object): value is ChannelMessageResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('attachment' in value) || value['attachment'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updateAt' in value) || value['updateAt'] === undefined) return false;
    return true;
}

export function ChannelMessageResponseFromJSON(json: any): ChannelMessageResponse {
    return ChannelMessageResponseFromJSONTyped(json, false);
}

export function ChannelMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
        'attachment': json['attachment'],
        'username': json['username'],
        'senderId': json['senderId'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'createdAt': (new Date(json['createdAt'])),
        'updateAt': (new Date(json['updateAt'])),
    };
}

export function ChannelMessageResponseToJSON(value?: ChannelMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'message': value['message'],
        'attachment': value['attachment'],
        'username': value['username'],
        'senderId': value['senderId'],
        'avatar': value['avatar'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updateAt': ((value['updateAt']).toISOString()),
    };
}

