/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelMessageResponse
 */
export interface ChannelMessageResponse {
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    attachment: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessageResponse
     */
    avatar?: string | null;
}

/**
 * Check if a given object implements the ChannelMessageResponse interface.
 */
export function instanceOfChannelMessageResponse(value: object): value is ChannelMessageResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('attachment' in value) || value['attachment'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ChannelMessageResponseFromJSON(json: any): ChannelMessageResponse {
    return ChannelMessageResponseFromJSONTyped(json, false);
}

export function ChannelMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'attachment': json['attachment'],
        'username': json['username'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function ChannelMessageResponseToJSON(value?: ChannelMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'attachment': value['attachment'],
        'username': value['username'],
        'avatar': value['avatar'],
    };
}

