/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageRequest
 */
export interface ChatMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageRequest
     */
    chat: string;
    /**
     * 
     * @type {Blob}
     * @memberof ChatMessageRequest
     */
    attachment?: Blob | null;
}

/**
 * Check if a given object implements the ChatMessageRequest interface.
 */
export function instanceOfChatMessageRequest(value: object): value is ChatMessageRequest {
    if (!('chat' in value) || value['chat'] === undefined) return false;
    return true;
}

export function ChatMessageRequestFromJSON(json: any): ChatMessageRequest {
    return ChatMessageRequestFromJSONTyped(json, false);
}

export function ChatMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chat': json['chat'],
        'attachment': json['attachment'] == null ? undefined : json['attachment'],
    };
}

export function ChatMessageRequestToJSON(value?: ChatMessageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chat': value['chat'],
        'attachment': value['attachment'],
    };
}

