/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChannelResponse
 */
export interface CreateChannelResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateChannelResponse
     */
    workspaceId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelResponse
     */
    name: string;
}

/**
 * Check if a given object implements the CreateChannelResponse interface.
 */
export function instanceOfCreateChannelResponse(value: object): value is CreateChannelResponse {
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateChannelResponseFromJSON(json: any): CreateChannelResponse {
    return CreateChannelResponseFromJSONTyped(json, false);
}

export function CreateChannelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChannelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workspaceId': json['workspaceId'],
        'name': json['name'],
    };
}

export function CreateChannelResponseToJSON(value?: CreateChannelResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workspaceId': value['workspaceId'],
        'name': value['name'],
    };
}

