/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkspaceResponse
 */
export interface CreateWorkspaceResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateWorkspaceResponse
     */
    workspaceId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspaceResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspaceResponse
     */
    joinCode: string;
}

/**
 * Check if a given object implements the CreateWorkspaceResponse interface.
 */
export function instanceOfCreateWorkspaceResponse(value: object): value is CreateWorkspaceResponse {
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('joinCode' in value) || value['joinCode'] === undefined) return false;
    return true;
}

export function CreateWorkspaceResponseFromJSON(json: any): CreateWorkspaceResponse {
    return CreateWorkspaceResponseFromJSONTyped(json, false);
}

export function CreateWorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workspaceId': json['workspaceId'],
        'name': json['name'],
        'joinCode': json['joinCode'],
    };
}

export function CreateWorkspaceResponseToJSON(value?: CreateWorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workspaceId': value['workspaceId'],
        'name': value['name'],
        'joinCode': value['joinCode'],
    };
}

