/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateUserRequest
 */
export interface DtoCreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateUserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the DtoCreateUserRequest interface.
 */
export function instanceOfDtoCreateUserRequest(value: object): value is DtoCreateUserRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function DtoCreateUserRequestFromJSON(json: any): DtoCreateUserRequest {
    return DtoCreateUserRequestFromJSONTyped(json, false);
}

export function DtoCreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function DtoCreateUserRequestToJSON(value?: DtoCreateUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

