/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChannel
 */
export interface GetChannel {
    /**
     * 
     * @type {string}
     * @memberof GetChannel
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetChannel
     */
    id: number;
}

/**
 * Check if a given object implements the GetChannel interface.
 */
export function instanceOfGetChannel(value: object): value is GetChannel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetChannelFromJSON(json: any): GetChannel {
    return GetChannelFromJSONTyped(json, false);
}

export function GetChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChannel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function GetChannelToJSON(value?: GetChannel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'id': value['id'],
    };
}

