/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetChannelResponse } from './GetChannelResponse';
import {
    GetChannelResponseFromJSON,
    GetChannelResponseFromJSONTyped,
    GetChannelResponseToJSON,
} from './GetChannelResponse';

/**
 * 
 * @export
 * @interface GetChannelsResponse
 */
export interface GetChannelsResponse {
    /**
     * 
     * @type {Array<GetChannelResponse>}
     * @memberof GetChannelsResponse
     */
    channels: Array<GetChannelResponse>;
}

/**
 * Check if a given object implements the GetChannelsResponse interface.
 */
export function instanceOfGetChannelsResponse(value: object): value is GetChannelsResponse {
    if (!('channels' in value) || value['channels'] === undefined) return false;
    return true;
}

export function GetChannelsResponseFromJSON(json: any): GetChannelsResponse {
    return GetChannelsResponseFromJSONTyped(json, false);
}

export function GetChannelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChannelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'channels': ((json['channels'] as Array<any>).map(GetChannelResponseFromJSON)),
    };
}

export function GetChannelsResponseToJSON(value?: GetChannelsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channels': ((value['channels'] as Array<any>).map(GetChannelResponseToJSON)),
    };
}

