/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChannelResponse
 */
export interface GetChannelResponse {
    /**
     * 
     * @type {number}
     * @memberof GetChannelResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetChannelResponse
     */
    name: string;
}

/**
 * Check if a given object implements the GetChannelResponse interface.
 */
export function instanceOfGetChannelResponse(value: object): value is GetChannelResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetChannelResponseFromJSON(json: any): GetChannelResponse {
    return GetChannelResponseFromJSONTyped(json, false);
}

export function GetChannelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChannelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function GetChannelResponseToJSON(value?: GetChannelResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

