/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMember
 */
export interface GetMember {
    /**
     * 
     * @type {number}
     * @memberof GetMember
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetMember
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetMember
     */
    avatar?: string | null;
}

/**
 * Check if a given object implements the GetMember interface.
 */
export function instanceOfGetMember(value: object): value is GetMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetMemberFromJSON(json: any): GetMember {
    return GetMemberFromJSONTyped(json, false);
}

export function GetMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function GetMemberToJSON(value?: GetMember | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'avatar': value['avatar'],
    };
}

