/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserWorkspaceResponse
 */
export interface GetUserWorkspaceResponse {
    /**
     * 
     * @type {number}
     * @memberof GetUserWorkspaceResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserWorkspaceResponse
     */
    name: string;
}

/**
 * Check if a given object implements the GetUserWorkspaceResponse interface.
 */
export function instanceOfGetUserWorkspaceResponse(value: object): value is GetUserWorkspaceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetUserWorkspaceResponseFromJSON(json: any): GetUserWorkspaceResponse {
    return GetUserWorkspaceResponseFromJSONTyped(json, false);
}

export function GetUserWorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserWorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function GetUserWorkspaceResponseToJSON(value?: GetUserWorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

