/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserWorkspaceResponse } from './GetUserWorkspaceResponse';
import {
    GetUserWorkspaceResponseFromJSON,
    GetUserWorkspaceResponseFromJSONTyped,
    GetUserWorkspaceResponseToJSON,
} from './GetUserWorkspaceResponse';

/**
 * 
 * @export
 * @interface GetUserWorkspacesResponse
 */
export interface GetUserWorkspacesResponse {
    /**
     * 
     * @type {Array<GetUserWorkspaceResponse>}
     * @memberof GetUserWorkspacesResponse
     */
    workspaces?: Array<GetUserWorkspaceResponse> | null;
}

/**
 * Check if a given object implements the GetUserWorkspacesResponse interface.
 */
export function instanceOfGetUserWorkspacesResponse(value: object): value is GetUserWorkspacesResponse {
    return true;
}

export function GetUserWorkspacesResponseFromJSON(json: any): GetUserWorkspacesResponse {
    return GetUserWorkspacesResponseFromJSONTyped(json, false);
}

export function GetUserWorkspacesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserWorkspacesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workspaces': json['workspaces'] == null ? undefined : ((json['workspaces'] as Array<any>).map(GetUserWorkspaceResponseFromJSON)),
    };
}

export function GetUserWorkspacesResponseToJSON(value?: GetUserWorkspacesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workspaces': value['workspaces'] == null ? undefined : ((value['workspaces'] as Array<any>).map(GetUserWorkspaceResponseToJSON)),
    };
}

