/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkspacePublicInfoResponse
 */
export interface GetWorkspacePublicInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof GetWorkspacePublicInfoResponse
     */
    name: string;
}

/**
 * Check if a given object implements the GetWorkspacePublicInfoResponse interface.
 */
export function instanceOfGetWorkspacePublicInfoResponse(value: object): value is GetWorkspacePublicInfoResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetWorkspacePublicInfoResponseFromJSON(json: any): GetWorkspacePublicInfoResponse {
    return GetWorkspacePublicInfoResponseFromJSONTyped(json, false);
}

export function GetWorkspacePublicInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspacePublicInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GetWorkspacePublicInfoResponseToJSON(value?: GetWorkspacePublicInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

