/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetChannel } from './GetChannel';
import {
    GetChannelFromJSON,
    GetChannelFromJSONTyped,
    GetChannelToJSON,
} from './GetChannel';

/**
 * 
 * @export
 * @interface GetWorkspaceResponse
 */
export interface GetWorkspaceResponse {
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceResponse
     */
    joinCode: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetWorkspaceResponse
     */
    isAdmin: boolean;
    /**
     * 
     * @type {Array<GetChannel>}
     * @memberof GetWorkspaceResponse
     */
    channels: Array<GetChannel>;
}

/**
 * Check if a given object implements the GetWorkspaceResponse interface.
 */
export function instanceOfGetWorkspaceResponse(value: object): value is GetWorkspaceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('joinCode' in value) || value['joinCode'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('channels' in value) || value['channels'] === undefined) return false;
    return true;
}

export function GetWorkspaceResponseFromJSON(json: any): GetWorkspaceResponse {
    return GetWorkspaceResponseFromJSONTyped(json, false);
}

export function GetWorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'joinCode': json['joinCode'],
        'isAdmin': json['isAdmin'],
        'channels': ((json['channels'] as Array<any>).map(GetChannelFromJSON)),
    };
}

export function GetWorkspaceResponseToJSON(value?: GetWorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'joinCode': value['joinCode'],
        'isAdmin': value['isAdmin'],
        'channels': ((value['channels'] as Array<any>).map(GetChannelToJSON)),
    };
}

