/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkspaceResponse
 */
export interface GetWorkspaceResponse {
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceResponse
     */
    joinCode?: string | null;
}

/**
 * Check if a given object implements the GetWorkspaceResponse interface.
 */
export function instanceOfGetWorkspaceResponse(value: object): value is GetWorkspaceResponse {
    return true;
}

export function GetWorkspaceResponseFromJSON(json: any): GetWorkspaceResponse {
    return GetWorkspaceResponseFromJSONTyped(json, false);
}

export function GetWorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'joinCode': json['joinCode'] == null ? undefined : json['joinCode'],
    };
}

export function GetWorkspaceResponseToJSON(value?: GetWorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'joinCode': value['joinCode'],
    };
}

