/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttperrorUnprocessableEntityApiResponse
 */
export interface HttperrorUnprocessableEntityApiResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HttperrorUnprocessableEntityApiResponse
     */
    errors?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof HttperrorUnprocessableEntityApiResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the HttperrorUnprocessableEntityApiResponse interface.
 */
export function instanceOfHttperrorUnprocessableEntityApiResponse(value: object): value is HttperrorUnprocessableEntityApiResponse {
    return true;
}

export function HttperrorUnprocessableEntityApiResponseFromJSON(json: any): HttperrorUnprocessableEntityApiResponse {
    return HttperrorUnprocessableEntityApiResponseFromJSONTyped(json, false);
}

export function HttperrorUnprocessableEntityApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttperrorUnprocessableEntityApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : json['errors'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HttperrorUnprocessableEntityApiResponseToJSON(value?: HttperrorUnprocessableEntityApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errors': value['errors'],
        'status': value['status'],
    };
}

