/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinCodeResponse
 */
export interface JoinCodeResponse {
    /**
     * 
     * @type {string}
     * @memberof JoinCodeResponse
     */
    joinCode: string;
}

/**
 * Check if a given object implements the JoinCodeResponse interface.
 */
export function instanceOfJoinCodeResponse(value: object): value is JoinCodeResponse {
    if (!('joinCode' in value) || value['joinCode'] === undefined) return false;
    return true;
}

export function JoinCodeResponseFromJSON(json: any): JoinCodeResponse {
    return JoinCodeResponseFromJSONTyped(json, false);
}

export function JoinCodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinCodeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'joinCode': json['joinCode'],
    };
}

export function JoinCodeResponseToJSON(value?: JoinCodeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'joinCode': value['joinCode'],
    };
}

