/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinWorkspaceRequest
 */
export interface JoinWorkspaceRequest {
    /**
     * 
     * @type {string}
     * @memberof JoinWorkspaceRequest
     */
    joinCode: string;
}

/**
 * Check if a given object implements the JoinWorkspaceRequest interface.
 */
export function instanceOfJoinWorkspaceRequest(value: object): value is JoinWorkspaceRequest {
    if (!('joinCode' in value) || value['joinCode'] === undefined) return false;
    return true;
}

export function JoinWorkspaceRequestFromJSON(json: any): JoinWorkspaceRequest {
    return JoinWorkspaceRequestFromJSONTyped(json, false);
}

export function JoinWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'joinCode': json['joinCode'],
    };
}

export function JoinWorkspaceRequestToJSON(value?: JoinWorkspaceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'joinCode': value['joinCode'],
    };
}

