/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorsResponse
 */
export interface ValidationErrorsResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorsResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorsResponse
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ValidationErrorsResponse interface.
 */
export function instanceOfValidationErrorsResponse(value: object): value is ValidationErrorsResponse {
    return true;
}

export function ValidationErrorsResponseFromJSON(json: any): ValidationErrorsResponse {
    return ValidationErrorsResponseFromJSONTyped(json, false);
}

export function ValidationErrorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ValidationErrorsResponseToJSON(value?: ValidationErrorsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

