/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WorkspaceUserRole = {
    User: 'User',
    Admin: 'Admin'
} as const;
export type WorkspaceUserRole = typeof WorkspaceUserRole[keyof typeof WorkspaceUserRole];


export function instanceOfWorkspaceUserRole(value: any): boolean {
    for (const key in WorkspaceUserRole) {
        if (Object.prototype.hasOwnProperty.call(WorkspaceUserRole, key)) {
            if (WorkspaceUserRole[key as keyof typeof WorkspaceUserRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkspaceUserRoleFromJSON(json: any): WorkspaceUserRole {
    return WorkspaceUserRoleFromJSONTyped(json, false);
}

export function WorkspaceUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceUserRole {
    return json as WorkspaceUserRole;
}

export function WorkspaceUserRoleToJSON(value?: WorkspaceUserRole | null): any {
    return value as any;
}

